#!/usr/bin/env bash


if [[ 1 -ne $# ]]; then
    echo "error..."
    exit 1
fi


cd "$1" || exit 1


file="server/drivers/mixed/mricp/src/Timer.cpp"
echo $file
ed -v "$file"<<EOF
H
2p
i
#include <unistd.h> // usleep(3)
.
p
wq
EOF
echo


file="server/drivers/shell/readlog.cc"
echo $file
ed -v "$file" <<EOF
H
687s/file/gzfile
641s/file/gzfile
wq
EOF
echo


file="client_libs/libplayerc++/playerclient.cc"
echo $file
ed -v "$file" <<EOF
H
166p
s/UTC/UTC_
wq
EOF
echo


file="libplayercore/Makefile.am"
echo $file
ed -v "$file" <<EOF
H
,s/python/python2
wq
EOF
echo


file="server/drivers/blackboard/localbb/Makefile.am"
echo $file
ed -v "$file" <<EOF
H
,s/dnl/#
wq
EOF
echo


file="utils/pmap/Makefile.am"
echo $file
ed -v "$file" <<EOF
H
24p
c
pmaptest_LDADD = -lpmap -llodo @GSL_LIBS@
.
p
wq
EOF


file="configure.ac"
echo $file
ed -v "$file" <<EOF
H
325p
s/LIB"/LIB -lboost_system"
wq
EOF
